### ISSUE TITLE
Investigate partial evaluation with or without Z3 for several use-cases

### ISSUE THREAD

**Issue by klizhentas** [gravitational/predicate-lang#31]
See discussion in this issue:

https://github.com/gravitational/teleport/pull/17700

**Comment by klizhentas** [comment]
I think we can build a simple partial evaluation engine in Go (that's where we need it) without Z3:

Consider logical expression:

`(logins == "root" && Node.labels["env"] == "prod")`. Partial evaluation in this case would be to bind Node.name variable, and we would get a simple logical expression:

`(logins == "root" && "prod" == "prod")`. We would then end up with a much simpler logical expression:

`(logins == "root")`

that we can evaluate to "root" in case if we pass variable logins.

@xacrimon please collect all cases where we need partial evaluation in the code (also please survey @fspmarshall on cases we need) and then please pass to @vitorenesduarte to build a partial evaluation in Golang branch you are working on.

The partial evaluator should provide strong guarantees on complexity, something < O(n)

**Comment by xacrimon** [comment]
Items where partial eval support matters:
- Allow node listing if Node rule matches without evaluating `node.login` field
- Figure out allowed logins from a policy

**Comment by xacrimon** [comment]
@fspmarshall @klizhentas I started looking into this and I have run into some hurdles. For some problems mentioned by @fspmarshall it doesn't seem to be the case that we need partial evaluation but it would be helpful for backwards compatible checks. The issue is that in order to support good partial evaluation like "is there any where we a user can create a token" or "determine possible logins from a predicate" we need to solve an NP-hard problem and we can't guarantee resolution of the mentioned questions within linear or logarithmic time.

**Comment by xacrimon** [comment]
One possible approach to this is to conclude that we cannot compute assignments like logins at critical path (we can do this during policy exports though, as this is a static case) but we resolve queries without asking for variable assignment i.e "are both these possible at the same time?"

**Comment by xacrimon** [comment]
If we want to remain in linear time, the only possible solution that remains is to precompute expressions for solutions which can then be evaluated in linear time. But this requires that we possibly rebuild policies to add new checks.

**Comment by klizhentas** [comment]
@xacrimon it's hard to solve the problem in abstract, that is why I would like to see all the use-cases we have today. We can support partial evaluation for logins for example, our most common use-case, because we have to bake this in the certs. What other use-cases we have now? 

Once we know all the use-cases, we may pursue different strategies for some scenarios, including precomputing some answers, and even using Z3 evaluation. That is why I would like us to get a full list of evaluations we are doing now and see what could really work. I think it's a very interesting problem! For example, we can build an evaluation Z3 server baked in Teleport and use GRPC flow to answer some questions and time-out if it takes too long, with partial degradation of the "oracle" service. Then things will still work, but won't have great UX .

**Comment by klizhentas** [comment]
For partial evaluation of logins, We will limit the amount of steps it takes, we will calculate how many steps we can process and limit it on predicate's constructor side.

**Comment by klizhentas** [comment]
Success criteria:

* Golang supports all the same use-cases with "partial eval" in our critical code paths
* Predicate has test examples in `test_teleport.py` that mirror those and render the same results
* We have an eval limit function that tells us if we can successfully partial eval the expression and predicate's constructor prevents writing expressions that are too complex to eval in critical code paths.

**Comment by xacrimon** [comment]
This PR provides a potential solution to this problem https://github.com/gravitational/teleport/pull/18732. As for the success criteria:
1. The above linked PR provides a way for the Go side to solve for potential logins, albeit at a cost as I ended up querying Z3 as I haven't managed to find a better solution, see my status update and the linked PR.
2. Due to the nature of this problem, it turns out we cannot determine how costly each step is due to the variety of theories at play and Z3 doesn't allow us to constrict this either. I have introduced a timeout feature within the partial solver to prevent unbounded or otherwise high running times but these are hard to check within the predicate CLI as the timeout depends on CPU execution speed of each machine

**Comment by xacrimon** [comment]
> @xacrimon it's hard to solve the problem in abstract, that is why I would like to see all the use-cases we have today. We can support partial evaluation for logins for example, our most common use-case, because we have to bake this in the certs. Another one I know is showing logins available for different servers. Partial eval will work for that scenario as well.
> 
> What other use-cases we have now?
> 
> Once we know all the use-cases, we may pursue different strategies for some scenarios, including precomputing some answers, and even using Z3 evaluation. That is why I would like us to get a full list of evaluations we are doing now and see what could really work. I think it's a very interesting problem! For example, we can build an evaluation Z3 server baked in Teleport and use GRPC flow to answer some questions and time-out if it takes too long, with partial degradation of the "oracle" service. Then things will still work, but won't have great UX .

After some exploration, I'm also not sure if we can bake this into certs. If we want to bake these into certs, we won't be able to properly calculate logins without removing the ability to look at the `Node` data within an `AccessNode` rule which seems detrimental to the concept of predicate. I think our best solution for usability here is to simply determine if a given login is valid when the SSH connection is made, which predicate allows us to do by just evaluating the predicate expression (without Z3) on the node with a given login.

**Comment by xacrimon** [comment]
Please also take a look at the linked PR.
